DatabricksPartnerHub
| extend Subscription = split(_ResourceId, "/")[2]
| extend Ressourcegroup = split(_ResourceId, "/")[4]
| extend Workspace = split(_ResourceId, "/")[-1]
| extend User = parse_json(Identity).email
| extend UserAgentIp = split(UserAgent, "/")[5]
| extend ComputeType = tostring(parse_json(RequestParams).compute_type)
| extend PartnerName = tostring(parse_json(RequestParams).partner_name)
| order by TimeGenerated desc
| project TimeGenerated, User, ActionName, Subscription, Ressourcegroup, Workspace, UserAgentIp, ComputeType, PartnerName