// Possible Alert: Count of rows >=1 in specific time period (e.g. aggregated and checked every 10 minutes)
DatabricksDBFS
| where ActionName == "delete"
| extend User = parse_json(Identity).email
| extend Subscription = split(_ResourceId, "/")[2]
| extend Ressourcegroup = split(_ResourceId, "/")[4]
| extend Workspace = split(_ResourceId, "/")[-1]
| extend FilePath = tostring(parse_json(RequestParams).path)
| order by TimeGenerated desc
| distinct TimeGenerated, tostring(User), tostring(Subscription), tostring(Ressourcegroup), tostring(Workspace), tostring(FilePath)