// Possible Alert:
DatabricksDBFS
| where ActionName == "delete"
| extend User = parse_json(Identity).email
| extend Subscription = split(_ResourceId, "/")[2]
| extend Ressourcegroup = split(_ResourceId, "/")[4]
| extend Workspace = split(_ResourceId, "/")[-1]
| extend FilePath = tostring(parse_json(RequestParams).path)
| order by TimeGenerated desc
| project TimeGenerated, User, Subscription, Ressourcegroup, Workspace, FilePath